app = "your-app-name"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builder = "heroku/buildpacks:20"

[env]
  NODE_ENV = "production"

[deploy]
  release_command = "npm run migrate" # if you have migrations, else remove

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443
