[build]
  image = "node:18"

[env]
  NODE_ENV = "production"
  TELEGRAM_BOT_TOKEN = "set_via_fly_secrets"
  ADMIN_USER = "Admin"
  ADMIN_PASS = "Pink2222"

[deploy]
  release_command = "bash ./build.sh"

[[mounts]]
  source = "gamblecodez-data"
  destination = "/data"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443