app = "gamblecodez-bitsler"
primary_region = "iad" # or choose your closest region

[build]
  # Remote build is needed for Android/Termux environments
  remote = true

[env]
  NODE_ENV = "production"

[deploy]
  strategy = "rolling"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
